name: "scp-28-stream"
spring:
  main:
    web-application-type: none
carparking:
  api-url-v1: https://carparking.sttindonesia.ac.id/api/v1
kafka:
  bootstrap-servers: "scp-28-boot.sttindonesia.ac.id:9092"
  consumer:
    group-id: "scp-28"
    auto-offset-reset: latest